"""Regression tests for the pre-first-commit readiness gate.

WHY THESE EXIST
---------------
A defect was found while writing scripts/repo_readiness_audit.py itself: the
remediation command for settings drift was generated by parsing the finding's
own human-readable text, and it picked up the LIVE value instead of the DECLARED
one. The report said "has_wiki: declared=False live=True" and then printed
`-F has_wiki=true` — so the instruction a junior operator was told to follow
would have re-applied the exact misconfiguration it had just reported. A second
defect in the same pass emitted unbalanced JSON braces in the secret-scanning
remediation payload, which would have failed at the moment of pasting.

docs/drift-findings.md D-22 records the governing lesson for this repository:
"an untested regex gate is a hypothesis, not a control." The commands this tool
tells a human to run are held to the same standard — they are the deliverable,
not commentary on it.

Run:  .venv/bin/python -m pytest tests/test_repo_readiness_audit.py -q
      make test
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path
from types import ModuleType

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "repo_readiness_audit.py"


def _load_gate() -> ModuleType:
    """Import scripts/repo_readiness_audit.py without making scripts/ a package."""
    spec = importlib.util.spec_from_file_location("repo_readiness_audit", SCRIPT)
    assert spec is not None, f"cannot build an import spec for {SCRIPT}"
    assert spec.loader is not None, "import spec has no loader"
    module = importlib.util.module_from_spec(spec)
    sys.modules["repo_readiness_audit"] = module
    spec.loader.exec_module(module)
    return module


rra = _load_gate()


# ── The inverted-remediation regression ──────────────────────────────────────


def test_drift_patch_command_sets_declared_value_not_live_value() -> None:
    """declared=False / live=True must produce `-F has_wiki=false`.

    This is the exact case the gate reported for jolarca-payments. The original
    implementation produced `has_wiki=true` here.
    """
    command = rra.drift_patch_command("jolarca-payments", [("has_wiki", False, True)])
    assert "-F has_wiki=false" in command
    assert "-F has_wiki=true" not in command


def test_drift_patch_command_sets_true_when_declaration_is_true() -> None:
    """The inverse direction, so the fix cannot be a hardcoded `false`."""
    command = rra.drift_patch_command("jolarca-payments", [("delete_branch_on_merge", True, False)])
    assert "-F delete_branch_on_merge=true" in command
    assert "-F delete_branch_on_merge=false" not in command


def test_drift_patch_command_covers_every_drifted_field() -> None:
    """A partial patch would leave drift behind and report clean next run."""
    pairs = [
        ("has_wiki", False, True),
        ("allow_merge_commit", False, True),
        ("allow_rebase_merge", False, True),
        ("delete_branch_on_merge", True, False),
    ]
    command = rra.drift_patch_command("jolarca-payments", pairs)
    for live_field, want, _ in pairs:
        assert f"-F {live_field}={'true' if want else 'false'}" in command


def test_describe_drift_and_patch_agree_on_direction() -> None:
    """The prose and the command must not contradict each other."""
    pairs = [("has_wiki", False, True)]
    assert "declared=False live=True" in rra.describe_drift(pairs)
    assert "-F has_wiki=false" in rra.drift_patch_command("r", pairs)


# ── The malformed-payload regression ─────────────────────────────────────────


def test_security_feature_command_emits_valid_json() -> None:
    """The payload must parse. The original had one closing brace too many."""
    command = rra.security_feature_command("jolarca-payments", "secret_scanning")
    payload = command.split("<<<'", 1)[1].rsplit("'", 1)[0]
    assert json.loads(payload) == {
        "security_and_analysis": {"secret_scanning": {"status": "enabled"}}
    }


def test_every_security_feature_produces_a_distinct_valid_payload() -> None:
    for feature, _severity in rra.SECURITY_FEATURES:
        command = rra.security_feature_command("repo", feature)
        payload = command.split("<<<'", 1)[1].rsplit("'", 1)[0]
        decoded = json.loads(payload)
        assert decoded["security_and_analysis"][feature]["status"] == "enabled"


def test_every_security_feature_has_its_own_rationale() -> None:
    """A Dependabot finding must not inherit the secret-scanning rationale."""
    assert set(rra.SECURITY_FEATURE_RATIONALE) == {f for f, _ in rra.SECURITY_FEATURES}
    rationales = list(rra.SECURITY_FEATURE_RATIONALE.values())
    assert len(set(rationales)) == len(rationales), "rationales must be distinct"


# ── Drift computation ────────────────────────────────────────────────────────


def test_registry_entry_overrides_policy_default() -> None:
    pairs = rra.compute_settings_drift(
        settings={"has_issues": True},
        defaults={"has_issues": False},
        meta={"has_issues": False},
    )
    assert pairs == [("has_issues", True, False)]


def test_policy_default_applies_when_registry_is_silent() -> None:
    pairs = rra.compute_settings_drift(
        settings={}, defaults={"has_wiki": False}, meta={"has_wiki": True}
    )
    assert pairs == [("has_wiki", False, True)]


def test_fields_absent_from_live_are_skipped_not_guessed() -> None:
    """A missing field is unverifiable, never evidence of agreement."""
    assert rra.compute_settings_drift({"has_wiki": False}, {}, {}) == []


def test_matching_settings_produce_no_drift() -> None:
    assert rra.compute_settings_drift({"has_wiki": False}, {}, {"has_wiki": False}) == []


# ── Verdict logic: "probably fine" is not a verdict ──────────────────────────


def _report(severity: str | None = None, unverified: bool = False) -> object:
    report = rra.RepoReport(repo="example")
    if severity is not None:
        report.add(rra.Finding("T-01", severity, "test", "summary", "evidence", "fix"))
    if unverified:
        report.note_unverified("test check", "could not be performed")
    report.decide()
    return report


def test_clean_repo_is_ready() -> None:
    assert _report().verdict == rra.VERDICT_READY


def test_s1_blocks() -> None:
    assert _report("S1").verdict == rra.VERDICT_BLOCKED


def test_s0_blocks() -> None:
    assert _report("S0").verdict == rra.VERDICT_BLOCKED


def test_s2_alone_is_ready_with_fixes() -> None:
    assert _report("S2").verdict == rra.VERDICT_FIXES


def test_s3_alone_is_ready_with_fixes() -> None:
    """Informational findings still prevent an unqualified READY."""
    assert _report("S3").verdict == rra.VERDICT_FIXES


def test_unverifiable_check_blocks_even_with_no_findings() -> None:
    """The D-23 rule: "could not check" must never be reported as "clean"."""
    assert _report(None, unverified=True).verdict == rra.VERDICT_BLOCKED


def test_severity_vocabulary_matches_the_findings_register() -> None:
    assert rra.SEVERITIES == ("S0", "S1", "S2", "S3")
    assert set(rra.BLOCKING_SEVERITIES) == {"S0", "S1"}


# ── Secret-scan corroboration ────────────────────────────────────────────────


def test_regex_hit_severity_depends_on_gitleaks_corroboration() -> None:
    """The jolarca-compliance false positive, pinned.

    A planted dummy AWS key sitting inside a documented negative test must not
    trigger a credential-rotation incident — but it must not be silently
    dropped either. Both directions are tested, plus the "scanner unavailable"
    case, which must stay S0 because assuming "probably a fixture" is how a real
    key ships.
    """
    hits = ["audits/AUDIT_REPORT.md:108 AWS access key ID [AKIAQ3EG...[redacted 20 chars]]"]
    root = Path("/tmp/example")
    assert rra._secret_finding("L-15", "tracked files", hits, None, root).severity == "S0"
    assert rra._secret_finding("L-15", "tracked files", hits, True, root).severity == "S0"
    assert rra._secret_finding("L-15", "tracked files", hits, False, root).severity == "S2"


def test_gitleaks_clean_regex_hit_does_not_block_the_verdict() -> None:
    """A gitleaks-clean regex hit yields READY-WITH-FIXES, not BLOCKED."""
    report = rra.RepoReport(repo="jolarca-compliance")
    report.add(
        rra._secret_finding("L-15", "tracked files", ["f:1 AWS key [redacted]"], False, Path("/t"))
    )
    report.decide()
    assert report.verdict == rra.VERDICT_FIXES


def test_corroborated_hit_blocks_the_verdict() -> None:
    report = rra.RepoReport(repo="jolarca-compliance")
    report.add(
        rra._secret_finding("L-15", "tracked files", ["f:1 AWS key [redacted]"], True, Path("/t"))
    )
    report.decide()
    assert report.verdict == rra.VERDICT_BLOCKED


def test_redaction_never_emits_the_full_secret() -> None:
    """The report is committed as evidence, so it must not become the leak."""
    token = "AKIAQ3EGFCLVW9YX7B2M"
    redacted = rra._redact(token)
    assert token not in redacted
    assert redacted.startswith(token[:8])
    assert "redacted" in redacted


def test_short_tokens_are_not_revealed_by_redaction() -> None:
    redacted = rra._redact("abcdefgh")
    assert "abcdefgh" not in redacted


# ── CODEOWNERS cross-project detection (ADR-0004 R4) ─────────────────────────


def test_jolarca_dev_codeowners_is_not_a_cross_project_violation(tmp_path: Path) -> None:
    """The marketplace org IS `jolarca-dev`, so a bare "jol-" prefix match flags
    the correctly-scoped entry. An earlier revision did exactly that and reported
    6 of 15 repositories as breaching ADR-0004 R4 when none of them were.
    """
    gh = tmp_path / ".github"
    gh.mkdir(parents=True)
    (gh / "CODEOWNERS").write_text("* @jolarca-dev/platform-admins\n")
    report = rra.RepoReport(repo="example")
    rra.check_codeowners(report, tmp_path)
    assert report.findings == []


def test_individual_owner_codeowners_is_not_a_cross_project_violation(tmp_path: Path) -> None:
    """`* @JourneyOfLife` is the D-20 remediation, not a violation: it carries no
    `org/team` slash, so it must not be matched at all."""
    gh = tmp_path / ".github"
    gh.mkdir(parents=True)
    (gh / "CODEOWNERS").write_text("* @JourneyOfLife\n")
    report = rra.RepoReport(repo="example")
    rra.check_codeowners(report, tmp_path)
    assert report.findings == []


def test_mission_platform_codeowners_is_flagged(tmp_path: Path) -> None:
    """The real violation must still be caught — the fix cannot be a blanket
    disable."""
    gh = tmp_path / ".github"
    gh.mkdir(parents=True)
    (gh / "CODEOWNERS").write_text(
        "* @journeyoflife-org/security\n/docs/ @jol-infrastructure/payments-owners\n"
    )
    report = rra.RepoReport(repo="example")
    rra.check_codeowners(report, tmp_path)
    finding = next((f for f in report.findings if f.fid == "L-11"), None)
    assert finding is not None, "cross-org CODEOWNERS was not detected"
    assert "journeyoflife-org/security" in finding.evidence
    assert "jol-infrastructure/payments-owners" in finding.evidence


def test_missing_codeowners_is_reported(tmp_path: Path) -> None:
    report = rra.RepoReport(repo="example")
    rra.check_codeowners(report, tmp_path)
    assert {f.fid for f in report.findings} == {"L-10"}


def test_no_forbidden_org_may_prefix_match_the_marketplace_org() -> None:
    """Invariant guard: nothing in the forbidden set may be a prefix of the org
    this control plane governs. Reintroducing a bare "jol-" fails here."""
    for forbidden in rra.FORBIDDEN_CODEOWNERS_ORGS:
        assert not rra.ORG.startswith(forbidden), (
            f"{forbidden!r} prefix-matches {rra.ORG!r} and would flag every "
            "correctly-scoped CODEOWNERS entry"
        )


def test_forbidden_orgs_match_the_drift_detect_allowlist() -> None:
    """drift_detect.check_codeowners() hardcodes the same two orgs. If the two
    gates disagree, one of them is wrong and neither can be trusted."""
    assert set(rra.FORBIDDEN_CODEOWNERS_ORGS) == {"journeyoflife-org", "jol-infrastructure"}


# ── Forbidden-path grading (templates are not secrets) ───────────────────────


def _make_repo(tmp_path: Path, files: dict[str, str]) -> Path:
    """Create a real git repository so check_local() is exercised end to end."""
    subprocess.run(["git", "init", "-b", "main", str(tmp_path)], check=True, capture_output=True)
    for name, body in files.items():
        target = tmp_path / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(
        [
            "git",
            "-c",
            "user.name=test",
            "-c",
            "user.email=test@example.com",
            "-c",
            "commit.gpgsign=false",
            "commit",
            "-m",
            "test init",
            "--no-verify",
        ],
        cwd=tmp_path,
        check=True,
        capture_output=True,
    )
    return tmp_path


def test_env_example_template_is_informational_not_stop_work(tmp_path: Path) -> None:
    """The flagship tracks three `.env*.example` templates carrying `CHANGE_ME`
    placeholders and "NEVER commit real values" headers. Grading them S1 blocked
    the repository for following good practice."""
    _make_repo(tmp_path, {".env.example": "DJANGO_SECRET_KEY=CHANGE_ME\n"})
    report = rra.RepoReport(repo="example", local_path=str(tmp_path))
    rra.check_local(report, {}, rra.secret_patterns({}))
    severities = {f.fid: f.severity for f in report.findings}
    assert severities.get("L-06b") == "S3"
    assert "L-06a" not in severities


def test_real_env_file_is_still_stop_work(tmp_path: Path) -> None:
    """The downgrade must not become a blanket exemption for .env files."""
    _make_repo(tmp_path, {".env": "STRIPE_SECRET=sk_live_x\n"})
    report = rra.RepoReport(repo="example", local_path=str(tmp_path))
    rra.check_local(report, {}, rra.secret_patterns({}))
    severities = {f.fid: f.severity for f in report.findings}
    assert severities.get("L-06a") == "S1"


def test_idea_directory_is_still_stop_work(tmp_path: Path) -> None:
    """D-28 regression: IDE metadata in the index must block."""
    _make_repo(tmp_path, {".idea/misc.xml": "<project/>\n"})
    report = rra.RepoReport(repo="example", local_path=str(tmp_path))
    rra.check_local(report, {}, rra.secret_patterns({}))
    assert {f.fid for f in report.findings if f.fid.startswith("L-06")} == {"L-06a"}


def test_terraform_state_in_the_index_is_stop_work(tmp_path: Path) -> None:
    _make_repo(tmp_path, {"terraform.tfstate": '{"serial": 1}\n'})
    report = rra.RepoReport(repo="example", local_path=str(tmp_path))
    rra.check_local(report, {}, rra.secret_patterns({}))
    assert any(f.fid == "L-06a" for f in report.findings)


def test_missing_origin_remote_is_reported(tmp_path: Path) -> None:
    """The jolarca-payments condition: two commits, no destination to push to."""
    _make_repo(tmp_path, {"README.md": "# x\n"})
    report = rra.RepoReport(repo="example", local_path=str(tmp_path))
    rra.check_local(report, {}, rra.secret_patterns({}))
    assert any(f.fid == "L-03" for f in report.findings)


def _git(args: list[str], cwd: Path) -> None:
    subprocess.run(
        [
            "git",
            "-c",
            "user.name=test",
            "-c",
            "user.email=t@example.com",
            "-c",
            "commit.gpgsign=false",
            *args,
        ],
        cwd=cwd,
        check=True,
        capture_output=True,
    )


def _commit(cwd: Path, message: str) -> None:
    _git(["add", "-A"], cwd)
    _git(["commit", "-m", message, "--no-verify"], cwd)


# ── Clone freshness (L-18) ───────────────────────────────────────────────────


def test_stale_clone_is_detected(tmp_path: Path) -> None:
    """A stale clone is how a remediated file gets resurrected.

    Live jolarca-compliance has NO .github/CODEOWNERS, yet its local clone still
    carries the pre-D-20 version naming mission-org teams. `origin/main` read as
    "in sync" because a remote-tracking ref only moves on fetch.
    """
    origin = tmp_path / "origin.git"
    subprocess.run(
        ["git", "init", "--bare", "-b", "main", str(origin)], check=True, capture_output=True
    )
    seed = _make_repo(tmp_path / "seed", {"README.md": "v1\n"})
    _git(["remote", "add", "origin", str(origin)], seed)
    _git(["push", "origin", "main"], seed)

    clone = tmp_path / "clone"
    subprocess.run(["git", "clone", str(origin), str(clone)], check=True, capture_output=True)

    # Advance the remote behind the clone's back; do NOT fetch in the clone.
    (seed / "README.md").write_text("v2 pushed by someone else\n", encoding="utf-8")
    _commit(seed, "second commit")
    _git(["push", "origin", "main"], seed)

    report = rra.RepoReport(repo="example", local_path=str(clone))
    rra.check_local(report, {}, rra.secret_patterns({}))
    assert any(f.fid == "L-18" for f in report.findings), [f.fid for f in report.findings]
    assert report.facts["remote_branch_exists"] is True


def test_clone_ahead_of_remote_is_not_stale(tmp_path: Path) -> None:
    """The normal pre-push state — local commits the remote lacks — is NOT a
    finding, or the gate would block every first commit it exists to permit."""
    origin = tmp_path / "origin.git"
    subprocess.run(
        ["git", "init", "--bare", "-b", "main", str(origin)], check=True, capture_output=True
    )
    seed = _make_repo(tmp_path / "seed", {"README.md": "v1\n"})
    _git(["remote", "add", "origin", str(origin)], seed)
    _git(["push", "origin", "main"], seed)

    clone = tmp_path / "clone"
    subprocess.run(["git", "clone", str(origin), str(clone)], check=True, capture_output=True)
    (clone / "NEW.md").write_text("local work awaiting push\n", encoding="utf-8")
    _commit(clone, "local commit not yet pushed")

    report = rra.RepoReport(repo="example", local_path=str(clone))
    rra.check_local(report, {}, rra.secret_patterns({}))
    assert not any(f.fid == "L-18" for f in report.findings), [f.fid for f in report.findings]


def test_no_remote_does_not_double_count_as_unverifiable(tmp_path: Path) -> None:
    """jolarca-payments has two commits and no origin. L-03 already blocks it;
    the failed ls-remote must not also be filed as a verification gap."""
    _make_repo(tmp_path, {"README.md": "# x\n"})
    report = rra.RepoReport(repo="example", local_path=str(tmp_path))
    rra.check_local(report, {}, rra.secret_patterns({}))
    assert any(f.fid == "L-03" for f in report.findings)
    assert not any("clone freshness" in u for u in report.unverified), report.unverified


# ── Policy-driven, not hardcoded ─────────────────────────────────────────────


def test_secret_patterns_come_from_policy() -> None:
    """policy/compliance-gates.yml#gates.secret_scan is the source of truth."""
    gates = {
        "gates": {
            "secret_scan": {
                "implementation": {
                    "custom_patterns": [
                        {
                            "pattern": "jolarca_(live|test)_[a-zA-Z0-9]{32,}",
                            "description": "API keys",
                        }
                    ]
                }
            }
        }
    }
    patterns = rra.secret_patterns(gates)
    assert patterns[0][0] == "jolarca_(live|test)_[a-zA-Z0-9]{32,}"
    # Built-ins are appended, never substituted.
    assert len(patterns) > len(gates["gates"]["secret_scan"]["implementation"]["custom_patterns"])


def test_forbidden_tracked_patterns_cover_the_d28_failure() -> None:
    """D-28: .idea/ and a scaffold file were the only things in the index."""
    joined = "\n".join(rra.FORBIDDEN_TRACKED_PATTERNS)
    for needle in (r"\.idea/", r"\.tfstate", r"\.env"):
        assert needle.replace("\\", "") in joined.replace("\\", "")


def test_codeowners_is_looked_for_in_all_three_honoured_locations() -> None:
    """D-20: this fleet keeps CODEOWNERS under .github/, so a root-only check
    would report a false absence."""
    assert ".github/CODEOWNERS" in rra.CODEOWNERS_CANDIDATES


def test_fleet_is_read_from_the_allow_list_not_hardcoded() -> None:
    """org_delivery_audit.sh hardcodes 7 of 16 repos and silently under-audits
    the rest. This gate must derive the fleet from repos/*.yml."""
    defined = rra.get_defined_repos()
    assert defined, "allow-list parsed as empty — the gate would audit nothing"
    on_disk = {p.stem for p in rra.REPOS_DIR.glob("*.yml")}
    assert set(defined) <= on_disk
    for name in defined:
        assert name == "jolarca" or name.startswith("jolarca-"), name


def test_license_template_is_read_from_settings_not_top_level(tmp_path: Path) -> None:
    """repos/jolarca.yml nests `license_template` under `settings`.

    The first implementation read it from the top level, so it was always None:
    every repo looked license-less and the flagship would have been reported as
    "LICENSE present although policy declares none" — the exact false positive
    compliance-gates.yml#license_check.scope_note forbids.
    """
    declared = rra.load_yaml(rra.REPOS_DIR / "jolarca.yml")
    assert declared["settings"]["license_template"] == "agpl-3.0"
    assert "license_template" not in declared, "nesting assumption changed — update the gate"

    report = rra.RepoReport(repo="jolarca")
    rra.check_license(report, tmp_path, declared)
    assert {f.fid for f in report.findings} == {"L-13a"}


def test_agpl_on_the_flagship_is_never_a_violation(tmp_path: Path) -> None:
    """A declared AGPL template plus a LICENSE file must produce zero findings."""
    (tmp_path / "LICENSE").write_text("GNU AFFERO GENERAL PUBLIC LICENSE Version 3\n")
    declared = {"visibility": "public", "settings": {"license_template": "agpl-3.0"}}
    report = rra.RepoReport(repo="jolarca")
    rra.check_license(report, tmp_path, declared)
    assert report.findings == []


def test_public_repo_without_license_is_informational_not_blocking(tmp_path: Path) -> None:
    """policy/repo-defaults.yml deliberately sets `license: null` for governance
    repos, so a missing LICENSE cannot be an S1 — that would fail the fleet on a
    policy choice rather than on a defect."""
    declared = {"visibility": "public", "settings": {}}
    report = rra.RepoReport(repo="jolarca-payments")
    rra.check_license(report, tmp_path, declared)
    findings = {f.fid: f for f in report.findings}
    assert set(findings) == {"L-13c"}
    assert findings["L-13c"].severity == "S3"
    report.decide()
    assert report.verdict == rra.VERDICT_FIXES
